param(
    [switch]$SkipDependencyInstall,
    [switch]$PullOllamaModels,
    [switch]$ForceEnv,
    [string]$OllamaChatModel = 'qwen3:latest',
    [string]$OllamaEmbeddingModel = 'nomic-embed-text:latest'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Write-Step {
    param(
        [string]$Message,
        [ConsoleColor]$Color = [ConsoleColor]::Cyan
    )

    Write-Host "`n==> $Message" -ForegroundColor $Color
}

function Test-CommandExists {
    param([string]$CommandName)

    return $null -ne (Get-Command $CommandName -ErrorAction SilentlyContinue)
}

function Assert-CommandExists {
    param(
        [string]$CommandName,
        [string]$InstallHint
    )

    if (-not (Test-CommandExists -CommandName $CommandName)) {
        throw "Required command '$CommandName' is not available. $InstallHint"
    }
}

function Get-NodeMajorVersion {
    $raw = (& node --version).Trim()
    if (-not $raw) {
        throw 'Could not determine Node.js version.'
    }

    $normalized = $raw.TrimStart('v')
    $major = ($normalized.Split('.')[0]) -as [int]
    if ($null -eq $major) {
        throw "Unexpected Node.js version format: $raw"
    }

    return @{ Raw = $raw; Major = $major }
}

function Install-Dependencies {
    param([string]$Path)

    if (-not (Test-Path $Path)) {
        throw "Project path not found: $Path"
    }

    Write-Host "Installing npm packages in $Path" -ForegroundColor Yellow
    Push-Location $Path
    try {
        npm install
    }
    finally {
        Pop-Location
    }
}

$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$backendPath = Join-Path $root 'backend'
$adminPath = Join-Path $root 'frontend\admin-dashboard'
$chatInterfacePath = Join-Path $root 'frontend\chat-interface'
$chatWidgetPath = Join-Path $root 'frontend\chat-widget'
$backendEnvPath = Join-Path $backendPath '.env'

Write-Step 'Validating required tools'
Assert-CommandExists -CommandName 'node' -InstallHint 'Install Node.js 18+ from https://nodejs.org/'
Assert-CommandExists -CommandName 'npm' -InstallHint 'npm ships with Node.js. Reinstall Node.js if needed.'

$nodeVersion = Get-NodeMajorVersion
if ($nodeVersion.Major -lt 18) {
    throw "Node.js 18+ is required. Detected $($nodeVersion.Raw)."
}
Write-Host "Node.js version detected: $($nodeVersion.Raw)" -ForegroundColor Green

Write-Step 'Preparing backend runtime folders'
@(
    (Join-Path $backendPath 'data'),
    (Join-Path $backendPath 'logs'),
    (Join-Path $backendPath 'uploads')
) | ForEach-Object {
    if (-not (Test-Path $_)) {
        New-Item -ItemType Directory -Path $_ | Out-Null
        Write-Host "Created $_" -ForegroundColor Yellow
    }
}

Write-Step 'Configuring backend .env for local-first development'
$localEnv = @"
# Local development defaults generated by setup-environment.ps1
NODE_ENV=development
BACKEND_PORT=3000
BACKEND_URL=http://localhost:3000
LOG_LEVEL=info

# Local in-memory fallback DB path is used automatically when PostgreSQL is unavailable
DATABASE_URL=postgresql://user:password@localhost:5432/aicsa_db
DB_POOL_SIZE=20
DB_TIMEOUT=5000

# Local vector + local LLM defaults
VECTOR_DB_PROVIDER=local
LLM_PROVIDER=ollama
OLLAMA_API_URL=http://localhost:11434
OLLAMA_MODEL=$OllamaChatModel
OLLAMA_EMBEDDING_MODEL=$OllamaEmbeddingModel

# Keep placeholders for optional cloud providers
OPENAI_API_KEY=
OPENAI_MODEL=gpt-4-turbo
EMBEDDING_MODEL=text-embedding-3-small
PINECONE_API_KEY=
PINECONE_ENVIRONMENT=us-west-2
PINECONE_INDEX_NAME=aicsa-prod

# Auth
JWT_SECRET=your_super_secret_jwt_key_at_least_32_chars_long
JWT_EXPIRY=900
REFRESH_TOKEN_EXPIRY=604800

# Redis disabled for local setup script path
REDIS_DISABLED=true
REDIS_URL=redis://localhost:6379
REDIS_PASSWORD=

# Email / escalation
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
ESCALATION_EMAIL=support@company.com

# RAG tuning
RETRIEVAL_TOP_K=5
CONFIDENCE_THRESHOLD=0.6
MAX_CONTEXT_TOKENS=2000
CHUNK_SIZE=1000
CHUNK_OVERLAP=200

# Upload + CORS
MAX_FILE_SIZE_MB=10
UPLOAD_DIR=./uploads
CORS_ORIGIN=http://localhost:3001,http://localhost:5173
"@

$shouldWriteEnv = $ForceEnv -or (-not (Test-Path $backendEnvPath))
if ($shouldWriteEnv) {
    Set-Content -Path $backendEnvPath -Value $localEnv -Encoding UTF8
    Write-Host "Wrote backend env file: $backendEnvPath" -ForegroundColor Green
}
else {
    Write-Host "Existing backend .env detected. Use -ForceEnv to overwrite." -ForegroundColor Yellow
}

if (-not $SkipDependencyInstall) {
    Write-Step 'Installing project dependencies'
    Install-Dependencies -Path $backendPath
    Install-Dependencies -Path $adminPath
    Install-Dependencies -Path $chatInterfacePath
    Install-Dependencies -Path $chatWidgetPath
}
else {
    Write-Step 'Skipping dependency installation (-SkipDependencyInstall)'
}

Write-Step 'Checking Ollama availability'
if (Test-CommandExists -CommandName 'ollama') {
    Write-Host 'Ollama command found.' -ForegroundColor Green

    if ($PullOllamaModels) {
        Write-Host "Pulling Ollama chat model: $OllamaChatModel" -ForegroundColor Yellow
        ollama pull $OllamaChatModel

        Write-Host "Pulling Ollama embedding model: $OllamaEmbeddingModel" -ForegroundColor Yellow
        ollama pull $OllamaEmbeddingModel
    }
    else {
        Write-Host 'Skipping model pull. Use -PullOllamaModels to pull required models now.' -ForegroundColor Yellow
    }
}
else {
    Write-Host 'Ollama command not found. Install from https://ollama.com/download' -ForegroundColor Yellow
    Write-Host "After install, run: ollama pull $OllamaChatModel" -ForegroundColor Gray
    Write-Host "Then run: ollama pull $OllamaEmbeddingModel" -ForegroundColor Gray
}

Write-Step 'Setup complete' -Color Green
Write-Host 'Next steps:' -ForegroundColor White
Write-Host '1) Start Ollama (if not already running).' -ForegroundColor Gray
Write-Host '2) Run .\start-all.ps1 to launch backend, admin dashboard, and chat interface.' -ForegroundColor Gray
Write-Host '3) Open http://localhost:3001 and log in with admin@aicsa.local / Admin@123.' -ForegroundColor Gray
